Update deps
CriminalInjuriesCompensationAuthority/q-base-config pull request #6
Opened 2021-05-10 15:53 UTC by armoj

Bump dependencies

2021-05-10 16:14 UTC, sinclairs requested changes

2021-05-10 16:14 UTC, sinclairs commented on index.js
> +        "prettier": "^2.2.1"
There are quite a few major version bumps... do they all work with the existing configs? https://github.com/CriminalInjuriesCompensationAuthority/q-base-config/tree/master/blocks

2021-05-11 08:31 UTC, armoj commented on index.js
> +        "prettier": "^2.2.1"
basically, the answer is: yes it is all still working.

https://jestjs.io/docs/configuration#testenvironment-string
https://prettier.io/docs/en/configuration.html
https://eslint.org/docs/rules/linebreak-style#enforce-consistent-linebreak-style-linebreak-style


* linting still working
* tests are passing
* pre-commit things are still doing their job

2021-05-11 14:58 UTC, sinclairs approved these changes

2021-05-11 15:32 UTC, sinclairs requested changes

2021-05-11 15:32 UTC, sinclairs commented on package.json
> +    "prettier": "^1.19.1"
Missing "eslint": "^6.8.0",

2021-05-11 15:37 UTC, sinclairs approved these changes

2021-05-11 15:42 UTC, merged